version: '3.4'

networks: 
  kong-net:

volumes:
  kong-ce-datastore:
    driver: local
    driver_opts:
      type: none
      device: $HOME/projects/docker/kong-ce
      o: bind

services:
  kong-migrations:
    image: revomatico/docker-kong-oidc
    command: kong migrations up #kong migrations bootstrap
    depends_on:
      - kong-ce-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_DB_DATABASE:-apigw}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_DB_USER:-kong}
    links:
      - kong-ce-db:db
    networks:
      - kong-net

  kong-ce-db:
    image: postgres:9.6
    volumes:
      - kong-ce-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_DB: ${KONG_DB_DATABASE:-apigw}
      POSTGRES_USER: ${KONG_DB_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD:-kong}
    restart: on-failure

  kong-ce:
    # build:
    #   context: .
    image: revomatico/docker-kong-oidc #eduardomourar/kong-alpine-oidc
    depends_on:
      - kong-ce-db
    links:
      - kong-ce-db:db
    networks:
      - kong-net
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8443:8443" # Listener  (SSL)
      - "8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_DB_DATABASE:-apigw}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_DB_USER:-kong}
      # KONG_PG_PORT: 5433
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS:          'oidc,azure-functions,aws-lambda'
    restart: on-failure

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong-ce
    networks:
      - kong-net
    links:
      - kong-ce-db:db
    ports:
      - "1337:1337" # konga
    environment:
      DB_ADAPTER: postgres
      # DB_PORT: '5433'
      DB_DATABASE: kongadb
      DB_HOST: db
      DB_USER: ${KONG_DB_USER:-kong}
      DB_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      NODE_ENV: development
    restart: on-failure

  # spring-okta:
  #   build:
  #     context: .
  #     dockerfile: spring-okta.Dockerfile
  #   # image: header-origin-example:latest
  #   depends_on:
  #     - kong-ce
  #   networks:
  #     - kong-net
  #   links:
  #     - kong-ce-db:db
  #   ports:
  #     - "4200:8000"
  #   restart: on-failure
